"""Hand-written fallback questions for CBSE Class 10 bank.

Used only when the live LLM fails for a chapter, so the bank is never missing
a chapter. Each chapter has exactly 6 questions: 4-5 easy, 1-2 medium.
"""

from typing import Any, Dict, List

# Keyed by chapter id prefix, e.g. "c10m-01".
FALLBACK: Dict[str, List[Dict[str, Any]]] = {
    "c10m-01": [
        {
            "question": "Using Euclid's division algorithm, the HCF of 867 and 255 is:",
            "options": ["3", "17", "51", "102"],
            "correct": 2,
            "difficulty": "easy",
            "explanation": "867 = 255 x 3 + 102, 255 = 102 x 2 + 51, 102 = 51 x 2 + 0, so the last non-zero remainder is 51.",
        },
        {
            "question": "The LCM of 6 and 20 is:",
            "options": ["2", "60", "120", "26"],
            "correct": 1,
            "explanation": "6 = 2 x 3 and 20 = 2^2 x 5, so LCM = 2^2 x 3 x 5 = 60.",
        },
        {
            "question": "Which of the following numbers has a terminating decimal expansion?",
            "options": ["17/8", "5/7", "12/11", "7/13"],
            "correct": 0,
            "explanation": "A rational number p/q in lowest terms terminates only if q is of the form 2^m x 5^n; here 8 = 2^3, so 17/8 terminates.",
        },
        {
            "question": "Every composite number can be expressed uniquely as a product of primes, apart from the order of factors. This is called the:",
            "options": ["Fundamental Theorem of Arithmetic", "Euclid's division lemma", "Sieve of Eratosthenes", "Law of large numbers"],
            "correct": 0,
            "explanation": "This statement is the Fundamental Theorem of Arithmetic, the basis of prime factorisation in the chapter on Real Numbers.",
        },
        {
            "question": "The largest number which divides 70 and 125 leaving remainders 5 and 8 respectively is:",
            "options": ["13", "65", "875", "175"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Subtract the remainders: HCF(70-5, 125-8) = HCF(65, 117) = 13.",
        },
        {
            "question": "If HCF(306, 657) = 9, then the LCM of 306 and 657 is:",
            "options": ["22338", "197442", "18", "27"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "HCF x LCM = product of the numbers, so LCM = (306 x 657)/9 = 22338.",
        },
    ],
    "c10m-02": [
        {
            "question": "The degree of the polynomial 5x^3 - 2x^2 + 7 is:",
            "options": ["3", "2", "1", "0"],
            "correct": 0,
            "explanation": "The degree is the highest power of x in the polynomial, which is 3 here.",
        },
        {
            "question": "The zero of the polynomial p(x) = 2x + 6 is:",
            "options": ["3", "-3", "6", "-6"],
            "correct": 1,
            "explanation": "Set 2x + 6 = 0, giving x = -3, the value at which p(x) becomes zero.",
        },
        {
            "question": "The sum of the zeroes of the quadratic polynomial x^2 - 7x + 10 is:",
            "options": ["7", "-7", "10", "3"],
            "correct": 0,
            "explanation": "For ax^2 + bx + c, the sum of zeroes is -b/a = -(-7)/1 = 7.",
        },
        {
            "question": "The product of the zeroes of the quadratic polynomial x^2 - 3x + 2 is:",
            "options": ["2", "3", "-3", "-2"],
            "correct": 0,
            "explanation": "The product of zeroes is c/a = 2/1 = 2.",
        },
        {
            "question": "A quadratic polynomial whose zeroes are 3 and -2 is:",
            "options": ["x^2 - x - 6", "x^2 + x - 6", "x^2 - x + 6", "x^2 + x + 6"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Sum of zeroes = 1 and product = -6, so the polynomial is x^2 - (sum)x + (product) = x^2 - x - 6.",
        },
        {
            "question": "If alpha and beta are the zeroes of x^2 - 5x + 6, then alpha^2 + beta^2 is:",
            "options": ["13", "25", "37", "11"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "alpha + beta = 5 and alpha x beta = 6, so alpha^2 + beta^2 = (alpha + beta)^2 - 2 alpha beta = 25 - 12 = 13.",
        },
    ],
    "c10m-03": [
        {
            "question": "The pair of linear equations x + y = 5 and x - y = 1 has:",
            "options": ["A unique solution", "Infinitely many solutions", "No solution", "Exactly two solutions"],
            "correct": 0,
            "explanation": "The coefficients are not proportional (1/1 is not 1/(-1)), so the lines intersect at a unique point.",
        },
        {
            "question": "A pair of linear equations a1x + b1y + c1 = 0 and a2x + b2y + c2 = 0 has no solution when:",
            "options": ["a1/a2 = b1/b2 but not c1/c2", "a1/a2 is not b1/b2", "a1/a2 = b1/b2 = c1/c2", "a1/a2 = c1/c2"],
            "correct": 0,
            "explanation": "Equal coefficient ratios but unequal constant ratios mean parallel lines, which never meet, so there is no solution.",
        },
        {
            "question": "The solution of the pair x + y = 7 and x - y = 3 is:",
            "options": ["x = 5, y = 2", "x = 2, y = 5", "x = 4, y = 3", "x = 3, y = 4"],
            "correct": 0,
            "explanation": "Adding the equations gives 2x = 10, so x = 5, and then y = 2.",
        },
        {
            "question": "For which value of k do the equations 2x + 3y = 7 and kx + 6y = 14 have infinitely many solutions?",
            "options": ["4", "6", "1", "3"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Infinitely many solutions need 2/k = 3/6 = 7/14, which gives k = 4.",
        },
        {
            "question": "The graph of the equation x = 3 is a straight line:",
            "options": ["Parallel to the y-axis", "Parallel to the x-axis", "Passing through (0, 3)", "Sloping upward"],
            "correct": 0,
            "explanation": "x = 3 means every point has x-coordinate 3, so the line is vertical, parallel to the y-axis.",
        },
        {
            "question": "The sum of two numbers is 20 and their difference is 4. The numbers are:",
            "options": ["12 and 8", "11 and 9", "13 and 7", "14 and 6"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Adding gives 2x = 24, so x = 12, and the other number is 20 - 12 = 8.",
        },
    ],
    "c10m-04": [
        {
            "question": "A quadratic equation in standard form is:",
            "options": ["ax^2 + bx + c = 0, a not equal to 0", "ax^2 + bx + c = 0, a = 0", "ax + b = 0", "ax^3 + bx + c = 0"],
            "correct": 0,
            "explanation": "A quadratic equation has degree exactly 2, so a cannot be zero in ax^2 + bx + c = 0.",
        },
        {
            "question": "The roots of x^2 - 5x + 6 = 0 are:",
            "options": ["2 and 3", "1 and 6", "-2 and -3", "5 and 6"],
            "correct": 0,
            "explanation": "x^2 - 5x + 6 = (x - 2)(x - 3) = 0, so x = 2 or x = 3.",
        },
        {
            "question": "The discriminant of the equation 2x^2 - 4x + 3 = 0 is:",
            "options": ["-8", "8", "16", "24"],
            "correct": 0,
            "explanation": "D = b^2 - 4ac = 16 - 4 x 2 x 3 = 16 - 24 = -8.",
        },
        {
            "question": "For which positive value of k does x^2 + kx + 4 = 0 have equal roots?",
            "options": ["4", "2", "8", "16"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Equal roots need D = k^2 - 16 = 0, so k = 4 (or -4); the positive value is 4.",
        },
        {
            "question": "If the roots of x^2 - 3x + 2 = 0 are alpha and beta, then 1/alpha + 1/beta is:",
            "options": ["3/2", "2/3", "3", "-3/2"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "1/alpha + 1/beta = (alpha + beta)/(alpha x beta) = 3/2.",
        },
        {
            "question": "The product of two consecutive positive integers is 306. The integers are:",
            "options": ["17 and 18", "16 and 19", "15 and 20", "18 and 19"],
            "correct": 0,
            "explanation": "x(x + 1) = 306 gives x^2 + x - 306 = 0, whose positive root is 17, so the integers are 17 and 18.",
        },
    ],
    "c10m-05": [
        {
            "question": "The common difference of the AP 3, 8, 13, 18, ... is:",
            "options": ["5", "3", "8", "-5"],
            "correct": 0,
            "explanation": "Each term is obtained by adding 5, so the common difference is 5.",
        },
        {
            "question": "The 10th term of the AP 2, 7, 12, ... is:",
            "options": ["47", "50", "52", "45"],
            "correct": 0,
            "explanation": "a10 = a + 9d = 2 + 9 x 5 = 47.",
        },
        {
            "question": "The sum of the first 10 natural numbers is:",
            "options": ["55", "50", "45", "60"],
            "correct": 0,
            "explanation": "Sum of the first n natural numbers is n(n+1)/2 = 10 x 11/2 = 55.",
        },
        {
            "question": "The sum of the first 20 terms of the AP 2, 5, 8, ... is:",
            "options": ["610", "620", "600", "590"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "S = 20/2 [2 x 2 + 19 x 3] = 10 x 61 = 610.",
        },
        {
            "question": "The 11th term from the end of the AP 10, 7, 4, ..., -62 is:",
            "options": ["-32", "-35", "-29", "-26"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Reversing the AP gives -62, -59, -56, ..., so the 11th term is -62 + 10 x 3 = -32.",
        },
        {
            "question": "The first term and common difference of the AP 4, 1, -2, -5, ... are:",
            "options": ["4 and -3", "4 and 3", "-5 and -3", "1 and 4"],
            "correct": 0,
            "explanation": "The first term is 4 and each term decreases by 3, so d = -3.",
        },
    ],
    "c10m-06": [
        {
            "question": "Two triangles are similar if their corresponding angles are equal and their corresponding sides are:",
            "options": ["Proportional", "Equal", "Perpendicular", "Parallel"],
            "correct": 0,
            "explanation": "Similar triangles have equal corresponding angles and proportional corresponding sides.",
        },
        {
            "question": "According to the Basic Proportionality Theorem, if a line is drawn parallel to one side of a triangle, it divides the other two sides:",
            "options": ["In the same ratio", "Equally", "In different ratios", "Into equal lengths"],
            "correct": 0,
            "explanation": "The theorem (of Thales) states the line cuts the other two sides in the same ratio.",
        },
        {
            "question": "If triangles ABC and DEF are similar and AB/DE = 1/2, the ratio of their areas is:",
            "options": ["1:4", "1:2", "2:1", "4:1"],
            "correct": 0,
            "explanation": "Areas of similar triangles are proportional to the squares of corresponding sides, so (1/2)^2 = 1:4.",
        },
        {
            "question": "In a right triangle ABC, right-angled at B, if AB = 6 cm and BC = 8 cm, then AC is:",
            "options": ["10 cm", "14 cm", "12 cm", "100 cm"],
            "correct": 0,
            "explanation": "By Pythagoras, AC = sqrt(6^2 + 8^2) = sqrt(100) = 10 cm.",
        },
        {
            "question": "In triangle ABC, D is on AB and E is on AC such that DE is parallel to BC. If AD = 3, DB = 4 and AE = 6, then EC is:",
            "options": ["8", "9", "7", "4.5"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "By the Basic Proportionality Theorem, AD/DB = AE/EC, so 3/4 = 6/EC and EC = 8.",
        },
        {
            "question": "In a right triangle, the square of the hypotenuse is equal to:",
            "options": ["The sum of the squares of the other two sides", "The difference of the squares of the other two sides", "The sum of the other two sides", "Twice the product of the other two sides"],
            "correct": 0,
            "explanation": "This is the statement of Pythagoras' theorem, used to relate the sides of a right triangle.",
        },
    ],
    "c10m-07": [
        {
            "question": "The distance between the points (0, 0) and (3, 4) is:",
            "options": ["5", "7", "25", "1"],
            "correct": 0,
            "explanation": "Distance = sqrt((3-0)^2 + (4-0)^2) = sqrt(25) = 5.",
        },
        {
            "question": "The midpoint of the segment joining (2, 4) and (6, 8) is:",
            "options": ["(4, 6)", "(8, 12)", "(2, 4)", "(4, 2)"],
            "correct": 0,
            "explanation": "The midpoint is ((2+6)/2, (4+8)/2) = (4, 6).",
        },
        {
            "question": "A point lying on the y-axis has its x-coordinate equal to:",
            "options": ["0", "1", "y", "Any real number"],
            "correct": 0,
            "explanation": "Every point on the y-axis has x-coordinate 0, such as (0, 5).",
        },
        {
            "question": "The distance between the points (2, 3) and (4, 1) is:",
            "options": ["2 sqrt(2)", "4 sqrt(2)", "2", "sqrt(8)"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Distance = sqrt((4-2)^2 + (1-3)^2) = sqrt(4 + 4) = 2 sqrt(2).",
        },
        {
            "question": "The area of the triangle formed by the points (0, 0), (6, 0) and (0, 8) is:",
            "options": ["24 square units", "48 square units", "12 square units", "14 square units"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "This right triangle has legs 6 and 8, so area = (1/2) x 6 x 8 = 24 square units.",
        },
        {
            "question": "The centroid of the triangle with vertices (0, 0), (4, 0) and (0, 6) is:",
            "options": ["(4/3, 2)", "(4/3, 6)", "(2, 3)", "(4, 6)"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The centroid is the average of the vertices: ((0+4+0)/3, (0+0+6)/3) = (4/3, 2).",
        },
    ],
    "c10m-08": [
        {
            "question": "The value of sin 30 degrees is:",
            "options": ["1/2", "sqrt(3)/2", "1", "0"],
            "correct": 0,
            "explanation": "In a 30-60-90 triangle the side opposite 30 degrees is half the hypotenuse, so sin 30 degrees = 1/2.",
        },
        {
            "question": "The value of tan 45 degrees is:",
            "options": ["1", "sqrt(3)", "1/2", "0"],
            "correct": 0,
            "explanation": "tan 45 degrees = sin 45 degrees / cos 45 degrees = (1/sqrt(2))/(1/sqrt(2)) = 1.",
        },
        {
            "question": "For any angle A, the identity connecting sine and cosine is:",
            "options": ["sin^2 A + cos^2 A = 1", "sin^2 A - cos^2 A = 1", "sin A + cos A = 1", "sin A cos A = 1"],
            "correct": 0,
            "explanation": "sin^2 A + cos^2 A = 1 is the fundamental trigonometric identity derived from Pythagoras' theorem.",
        },
        {
            "question": "If tan A = 3/4, then sin A is:",
            "options": ["3/5", "4/5", "3/4", "5/3"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "tan A = 3/4 means opposite = 3 and adjacent = 4, so the hypotenuse is 5 and sin A = 3/5.",
        },
        {
            "question": "The value of sin 30 degrees cos 60 degrees + cos 30 degrees sin 60 degrees is:",
            "options": ["1", "1/2", "sqrt(3)/2", "1/4"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "(1/2)(1/2) + (sqrt(3)/2)(sqrt(3)/2) = 1/4 + 3/4 = 1.",
        },
        {
            "question": "The value of sec^2 A - tan^2 A is:",
            "options": ["1", "0", "2", "tan A"],
            "correct": 0,
            "explanation": "Dividing sin^2 A + cos^2 A = 1 by cos^2 A gives tan^2 A + 1 = sec^2 A, so sec^2 A - tan^2 A = 1.",
        },
    ],
    "c10m-09": [
        {
            "question": "The angle of elevation of an object is measured from the observer's eye:",
            "options": ["With the horizontal when the object is above", "With the vertical when the object is above", "With the horizontal when the object is below", "Between two vertical lines"],
            "correct": 0,
            "explanation": "The angle of elevation is the angle between the line of sight and the horizontal when looking at an object above eye level.",
        },
        {
            "question": "A tower casts a shadow of length equal to its height. The angle of elevation of the sun is:",
            "options": ["45 degrees", "30 degrees", "60 degrees", "90 degrees"],
            "correct": 0,
            "explanation": "If height = shadow length, tan of the angle = 1, so the angle of elevation is 45 degrees.",
        },
        {
            "question": "The value of sin 45 degrees is:",
            "options": ["1/sqrt(2)", "1/2", "sqrt(3)/2", "sqrt(2)"],
            "correct": 0,
            "explanation": "In an isosceles right triangle both acute angles are 45 degrees and sin 45 degrees = 1/sqrt(2).",
        },
        {
            "question": "From the top of a 10 m high tower, the angle of depression of a point on the ground is 45 degrees. The distance of the point from the foot of the tower is:",
            "options": ["10 m", "20 m", "5 m", "10/sqrt(2) m"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The angle of depression equals the angle of elevation of the tower top from that point, so tan 45 degrees = 10/d and d = 10 m.",
        },
        {
            "question": "A kite flying at a height of 30 m has its string making an angle of 60 degrees with the horizontal. The length of the string is:",
            "options": ["20 sqrt(3) m", "30 sqrt(3) m", "60 m", "15 m"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "sin 60 degrees = 30/L, so L = 30/(sqrt(3)/2) = 60/sqrt(3) = 20 sqrt(3) m.",
        },
        {
            "question": "The angle of depression is the angle between the line of sight and the horizontal when the object is:",
            "options": ["Below the observer's eye level", "Above the observer's eye level", "At the same level as the observer", "Directly overhead"],
            "correct": 0,
            "explanation": "When looking down at an object below eye level, the angle between the line of sight and the horizontal is the angle of depression.",
        },
    ],
    "c10m-10": [
        {
            "question": "The number of tangents that can be drawn from an external point to a circle is:",
            "options": ["2", "1", "0", "3"],
            "correct": 0,
            "explanation": "Exactly two tangents can be drawn from an external point to a circle.",
        },
        {
            "question": "A tangent to a circle at the point of contact is:",
            "options": ["Perpendicular to the radius", "Parallel to the radius", "Parallel to the diameter", "Perpendicular to the chord"],
            "correct": 0,
            "explanation": "The tangent at a point is perpendicular to the radius drawn to that point of contact.",
        },
        {
            "question": "The angle between the tangent and the radius at the point of contact is:",
            "options": ["90 degrees", "60 degrees", "45 degrees", "180 degrees"],
            "correct": 0,
            "explanation": "The radius and tangent are perpendicular at the point of contact, so the angle is 90 degrees.",
        },
        {
            "question": "From a point P, the lengths of the two tangents drawn to a circle are:",
            "options": ["Equal", "Unequal", "Always double the radius", "Half the radius"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The lengths of tangents from an external point to a circle are always equal, a standard theorem of the chapter.",
        },
        {
            "question": "PA and PB are tangents from P to a circle with centre O, and angle APB = 60 degrees. The angle AOB at the centre is:",
            "options": ["120 degrees", "60 degrees", "90 degrees", "30 degrees"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "OA and OB are perpendicular to the tangents, so in quadrilateral PAOB, 90 + 90 + 60 + angle AOB = 360, giving 120 degrees.",
        },
        {
            "question": "A tangent to a circle intersects the circle at:",
            "options": ["Exactly one point", "Two points", "Three points", "No point"],
            "correct": 0,
            "explanation": "By definition a tangent touches the circle at exactly one point, unlike a secant which cuts at two points.",
        },
    ],
    "c10m-11": [
        {
            "question": "To divide a line segment AB internally in the ratio 5:7, the number of equal parts marked on the ray drawn from A is:",
            "options": ["12", "5", "7", "2"],
            "correct": 0,
            "explanation": "The segment is divided in the ratio 5:7, so the ray is marked into 5 + 7 = 12 equal parts.",
        },
        {
            "question": "To construct a tangent to a circle at a point P on it, the first step is to:",
            "options": ["Join P to the centre O", "Draw a chord through P", "Draw any secant through P", "Draw the diameter at P"],
            "correct": 0,
            "explanation": "We first draw the radius OP and then construct the tangent at P perpendicular to OP.",
        },
        {
            "question": "To divide a segment AB of length 8 cm internally in the ratio 3:5, the number of equal parts to be marked on the ray is:",
            "options": ["8", "3", "5", "15"],
            "correct": 0,
            "explanation": "The number of equal parts equals the sum of the ratio numbers, 3 + 5 = 8.",
        },
        {
            "question": "When constructing a triangle similar to a given triangle with scale factor 3/5, the number of points marked on the ray is:",
            "options": ["5", "3", "8", "2"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The scale factor 3/5 means we divide the side in the ratio 3:5, so 5 points are marked on the ray.",
        },
        {
            "question": "To construct the tangents from an external point P to a circle with centre O, the first step is to:",
            "options": ["Join OP and find its midpoint", "Draw a tangent at P", "Draw a diameter", "Join P to any point on the circle"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "We join P to the centre O, then draw a circle with OP as diameter; its intersections with the given circle are the points of contact.",
        },
        {
            "question": "The tangents drawn from an external point P to a circle touch the circle at two points. These two points are found by:",
            "options": ["Drawing a circle with OP as diameter", "Drawing a chord through P", "Extending OP beyond O", "Drawing a line parallel to OP"],
            "correct": 0,
            "explanation": "A circle drawn with OP as diameter cuts the given circle at the two points of contact, since angle of contact is 90 degrees.",
        },
    ],
    "c10m-12": [
        {
            "question": "The area of a circle of radius 7 cm is:",
            "options": ["154 sq cm", "44 sq cm", "308 sq cm", "22 sq cm"],
            "correct": 0,
            "explanation": "Area = pi r^2 = (22/7) x 7 x 7 = 154 sq cm.",
        },
        {
            "question": "The circumference of a circle of radius 14 cm is:",
            "options": ["88 cm", "44 cm", "154 cm", "176 cm"],
            "correct": 0,
            "explanation": "Circumference = 2 pi r = 2 x (22/7) x 14 = 88 cm.",
        },
        {
            "question": "The area of a semicircle of radius r is:",
            "options": ["(1/2) pi r^2", "pi r^2", "2 pi r", "pi r"],
            "correct": 0,
            "explanation": "A semicircle is half of a full circle, so its area is (1/2) pi r^2.",
        },
        {
            "question": "The area of the minor sector of a circle of radius 6 cm with central angle 60 degrees is:",
            "options": ["6 pi sq cm", "36 pi sq cm", "12 pi sq cm", "3 pi sq cm"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Sector area = (60/360) x pi x 6^2 = (1/6) x 36 pi = 6 pi sq cm.",
        },
        {
            "question": "The length of the arc of a sector of radius 7 cm and central angle 90 degrees is:",
            "options": ["11 cm", "22 cm", "44 cm", "5.5 cm"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Arc length = (90/360) x 2 pi r = (1/4) x 2 x (22/7) x 7 = 11 cm.",
        },
        {
            "question": "The area of a quadrant (quarter circle) of radius 7 cm is:",
            "options": ["38.5 sq cm", "77 sq cm", "154 sq cm", "19.25 sq cm"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Quadrant area = (1/4) x pi r^2 = (1/4) x (22/7) x 49 = 38.5 sq cm.",
        },
    ],
    "c10m-13": [
        {
            "question": "The volume of a cylinder of radius r and height h is:",
            "options": ["pi r^2 h", "2 pi r h", "pi r h", "(1/3) pi r^2 h"],
            "correct": 0,
            "explanation": "The volume of a cylinder is the area of its base times its height, pi r^2 h.",
        },
        {
            "question": "The volume of a cone of radius r and height h is:",
            "options": ["(1/3) pi r^2 h", "pi r^2 h", "(4/3) pi r^3", "2 pi r h"],
            "correct": 0,
            "explanation": "A cone holds one third of the volume of a cylinder of the same base and height.",
        },
        {
            "question": "The volume of a sphere of radius 3 cm is:",
            "options": ["36 pi cu cm", "12 pi cu cm", "108 pi cu cm", "27 pi cu cm"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Volume = (4/3) pi r^3 = (4/3) pi x 27 = 36 pi cu cm.",
        },
        {
            "question": "A cone has base radius 3 cm and height 4 cm. Its curved surface area is:",
            "options": ["15 pi sq cm", "12 pi sq cm", "20 pi sq cm", "9 pi sq cm"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Slant height l = sqrt(3^2 + 4^2) = 5 cm, so CSA = pi r l = pi x 3 x 5 = 15 pi sq cm.",
        },
        {
            "question": "The surface area of a sphere of radius r is:",
            "options": ["4 pi r^2", "(4/3) pi r^3", "2 pi r^2", "pi r^2"],
            "correct": 0,
            "explanation": "The total surface area of a sphere is 4 pi r^2.",
        },
        {
            "question": "Two cubes of side 6 cm each are joined end to end. The surface area of the resulting cuboid is:",
            "options": ["360 sq cm", "432 sq cm", "216 sq cm", "720 sq cm"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The cuboid is 12 x 6 x 6, so SA = 2(12 x 6 + 12 x 6 + 6 x 6) = 2(180) = 360 sq cm.",
        },
    ],
    "c10m-14": [
        {
            "question": "The mean of the data 4, 6, 8, 10, 12 is:",
            "options": ["8", "10", "9", "7"],
            "correct": 0,
            "explanation": "Mean = (4 + 6 + 8 + 10 + 12)/5 = 40/5 = 8.",
        },
        {
            "question": "The median of the data 3, 5, 7, 9, 11 is:",
            "options": ["7", "5", "9", "3"],
            "correct": 0,
            "explanation": "The middle value of the five ordered observations is 7.",
        },
        {
            "question": "The mode of the data 1, 2, 2, 3, 4, 2 is:",
            "options": ["2", "1", "3", "4"],
            "correct": 0,
            "explanation": "The mode is the most frequent observation, and 2 appears three times.",
        },
        {
            "question": "The class mark of the class interval 10-20 is:",
            "options": ["15", "10", "20", "30"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The class mark is the midpoint: (10 + 20)/2 = 15.",
        },
        {
            "question": "The median of the six observations 5, 7, 9, 11, 13, 15 is:",
            "options": ["10", "9", "11", "12"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "For an even number of observations, the median is the mean of the two middle values: (9 + 11)/2 = 10.",
        },
        {
            "question": "The mean of five numbers is 8. If four of them are 6, 8, 9 and 10, the fifth number is:",
            "options": ["7", "8", "5", "6"],
            "correct": 0,
            "explanation": "The total is 5 x 8 = 40, and the given four add to 33, so the fifth is 40 - 33 = 7.",
        },
    ],
    "c10s-01": [
        {
            "question": "In a balanced chemical equation, the numbers written before the formulas are called:",
            "options": ["Coefficients", "Valencies", "Indices", "Reactants"],
            "correct": 0,
            "explanation": "Coefficients are the numbers placed before formulas to balance the number of atoms of each element.",
        },
        {
            "question": "The reaction 2H2 + O2 gives 2H2O is an example of a:",
            "options": ["Combination reaction", "Decomposition reaction", "Displacement reaction", "Double displacement reaction"],
            "correct": 0,
            "explanation": "Two reactants combine to form a single product, so it is a combination reaction.",
        },
        {
            "question": "Heating ferrous sulphate crystals, which turn green to brown, is an example of:",
            "options": ["Thermal decomposition", "Combination", "Displacement", "Double displacement"],
            "correct": 0,
            "explanation": "Ferrous sulphate decomposes on heating into ferric oxide, sulphur dioxide and sulphur trioxide, a thermal decomposition.",
        },
        {
            "question": "In the balanced equation 2Pb(NO3)2 gives 2PbO + 4NO2 + O2, the number of nitrogen dioxide molecules formed is:",
            "options": ["4", "2", "1", "8"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Lead nitrate decomposes on heating and the balanced equation shows 4 molecules of NO2 per 2 molecules of Pb(NO3)2.",
        },
        {
            "question": "Digestion of food in our body is an example of a:",
            "options": ["Decomposition reaction", "Combination reaction", "Displacement reaction", "Redox reaction only"],
            "correct": 0,
            "explanation": "Complex food molecules are broken down into simpler substances, so digestion is a decomposition reaction.",
        },
        {
            "question": "Rusting of iron takes place in the presence of:",
            "options": ["Oxygen and moisture", "Oxygen only", "Carbon dioxide only", "Nitrogen and moisture"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Both oxygen and water are needed for rusting; that is why a fully dry or oiled iron surface does not rust.",
        },
    ],
    "c10s-02": [
        {
            "question": "The pH of a neutral solution is:",
            "options": ["7", "0", "14", "1"],
            "correct": 0,
            "explanation": "A neutral solution like pure water has pH exactly 7 at 25 degrees C.",
        },
        {
            "question": "The reaction between an acid and a base to form salt and water is called:",
            "options": ["Neutralisation", "Oxidation", "Displacement", "Sublimation"],
            "correct": 0,
            "explanation": "Neutralisation is the reaction of an acid with a base to produce a salt and water.",
        },
        {
            "question": "Acids turn blue litmus solution:",
            "options": ["Red", "Blue", "Green", "Yellow"],
            "correct": 0,
            "explanation": "Blue litmus turns red in acidic solutions; it is the standard test for acids.",
        },
        {
            "question": "The chemical formula of washing soda is:",
            "options": ["Na2CO3.10H2O", "NaHCO3", "NaOH", "NaCl"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Washing soda is sodium carbonate decahydrate, Na2CO3.10H2O, obtained from sodium carbonate by crystallisation.",
        },
        {
            "question": "Baking soda used in antacids is chemically:",
            "options": ["Sodium hydrogencarbonate", "Sodium carbonate", "Sodium chloride", "Sodium hydroxide"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Baking soda is sodium hydrogencarbonate (NaHCO3), which neutralises excess acid in the stomach.",
        },
        {
            "question": "A solution with pH 2 is:",
            "options": ["More acidic than a solution with pH 6", "Less acidic than a solution with pH 6", "Neutral", "Basic"],
            "correct": 0,
            "explanation": "Lower pH means higher acidity; each unit of pH corresponds to a tenfold change in hydrogen ion concentration.",
        },
    ],
    "c10s-03": [
        {
            "question": "The only metal that is liquid at room temperature is:",
            "options": ["Mercury", "Sodium", "Copper", "Aluminium"],
            "correct": 0,
            "explanation": "Mercury is the only metal that is liquid at room temperature; it is used in thermometers.",
        },
        {
            "question": "The most reactive metal among the following is:",
            "options": ["Potassium", "Zinc", "Iron", "Copper"],
            "correct": 0,
            "explanation": "Potassium is at the top of the reactivity series and reacts violently with cold water.",
        },
        {
            "question": "The non-metal that is a good conductor of electricity is:",
            "options": ["Graphite", "Sulphur", "Phosphorus", "Nitrogen"],
            "correct": 0,
            "explanation": "Graphite, an allotrope of carbon, conducts electricity because of free electrons in its structure.",
        },
        {
            "question": "Aqua regia, used to dissolve gold, is a mixture of concentrated HCl and HNO3 in the ratio:",
            "options": ["3:1", "1:3", "1:1", "2:1"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Aqua regia is 3 parts concentrated hydrochloric acid and 1 part concentrated nitric acid by volume.",
        },
        {
            "question": "In the reaction Zn + CuSO4 gives ZnSO4 + Cu, zinc:",
            "options": ["Displaces copper from its salt solution", "Is less reactive than copper", "Forms an alloy with copper", "Does not react"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Zinc is more reactive than copper, so it displaces copper from copper sulphate solution; the blue colour fades.",
        },
        {
            "question": "Sodium metal is stored in kerosene because it:",
            "options": ["Reacts vigorously with air and water", "Melts at room temperature", "Is very costly", "Evaporates easily"],
            "correct": 0,
            "explanation": "Sodium reacts vigorously with oxygen and water, so it is stored in kerosene to keep it away from both.",
        },
    ],
    "c10s-04": [
        {
            "question": "The valency of carbon is:",
            "options": ["4", "2", "3", "1"],
            "correct": 0,
            "explanation": "Carbon has four electrons in its outermost shell, so it shares four electrons and has valency 4.",
        },
        {
            "question": "The property of carbon atoms to link with other carbon atoms to form chains is called:",
            "options": ["Catenation", "Hydrogenation", "Isomerism", "Polymerisation"],
            "correct": 0,
            "explanation": "Catenation is the self-linking of carbon atoms to form long chains, rings and branches.",
        },
        {
            "question": "The functional group -OH present in a compound makes it an:",
            "options": ["Alcohol", "Aldehyde", "Ketone", "Carboxylic acid"],
            "correct": 0,
            "explanation": "The -OH group is the characteristic functional group of alcohols such as ethanol.",
        },
        {
            "question": "Vinegar contains, in diluted form, the compound:",
            "options": ["Ethanoic acid", "Ethanol", "Methanol", "Formaldehyde"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Vinegar is a 5-8 percent aqueous solution of ethanoic acid (acetic acid).",
        },
        {
            "question": "Ethanol can be converted to ethene by heating with concentrated sulphuric acid. This reaction is called:",
            "options": ["Dehydration", "Hydrogenation", "Combustion", "Esterification"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Concentrated sulphuric acid removes a water molecule from ethanol, dehydrating it to ethene.",
        },
        {
            "question": "The hydrocarbon with a double bond between its carbon atoms is:",
            "options": ["Ethene", "Ethane", "Propane", "Methane"],
            "correct": 0,
            "explanation": "Ethene (C2H4) has a double bond; ethane, propane and methane have only single bonds.",
        },
    ],
    "c10s-05": [
        {
            "question": "The green pigment that absorbs sunlight in photosynthesis is:",
            "options": ["Chlorophyll", "Haemoglobin", "Carotene", "Melanin"],
            "correct": 0,
            "explanation": "Chlorophyll in the chloroplasts absorbs sunlight needed to convert carbon dioxide and water into glucose.",
        },
        {
            "question": "Photosynthesis takes place in the:",
            "options": ["Chloroplasts", "Mitochondria", "Nucleus", "Ribosomes"],
            "correct": 0,
            "explanation": "Chloroplasts contain chlorophyll and are the sites of photosynthesis in plant cells.",
        },
        {
            "question": "Amoeba takes in food by a process called:",
            "options": ["Endocytosis", "Excretion", "Diffusion", "Transpiration"],
            "correct": 0,
            "explanation": "Amoeba engulfs food particles by surrounding them with its cell membrane, a process called endocytosis.",
        },
        {
            "question": "In humans, urea is formed in the:",
            "options": ["Liver", "Kidneys", "Lungs", "Heart"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The liver converts excess ammonia into urea, which the kidneys then filter out of the blood as urine.",
        },
        {
            "question": "The blood vessel that carries oxygenated blood from the lungs to the heart is the:",
            "options": ["Pulmonary vein", "Pulmonary artery", "Aorta", "Vena cava"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The pulmonary vein is the only vein carrying oxygenated blood, from the lungs to the left atrium.",
        },
        {
            "question": "The blood component that helps in clotting at the site of an injury is:",
            "options": ["Platelets", "Red blood cells", "White blood cells", "Plasma"],
            "correct": 0,
            "explanation": "Platelets plug the wound and release chemicals that help form a clot and stop bleeding.",
        },
    ],
    "c10s-06": [
        {
            "question": "The reflex action is controlled by the:",
            "options": ["Spinal cord", "Cerebrum", "Cerebellum", "Medulla"],
            "correct": 0,
            "explanation": "Reflex actions are rapid, automatic responses coordinated by the spinal cord without involving the brain.",
        },
        {
            "question": "The hormone that regulates the level of sugar in the blood is:",
            "options": ["Insulin", "Thyroxine", "Adrenaline", "Growth hormone"],
            "correct": 0,
            "explanation": "Insulin, secreted by the pancreas, lowers blood sugar; its deficiency causes diabetes.",
        },
        {
            "question": "The growth hormone is secreted by the:",
            "options": ["Pituitary gland", "Thyroid gland", "Adrenal gland", "Pancreas"],
            "correct": 0,
            "explanation": "The pituitary gland at the base of the brain secretes growth hormone that controls body growth.",
        },
        {
            "question": "The growth of a plant shoot towards light is called:",
            "options": ["Phototropism", "Geotropism", "Hydrotropism", "Chemotropism"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Auxin moves to the shaded side and makes the shoot bend towards light, a response called phototropism.",
        },
        {
            "question": "The deficiency of iodine in our diet causes goitre because iodine is needed to make:",
            "options": ["Thyroxine", "Insulin", "Adrenaline", "Testosterone"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The thyroid gland needs iodine to synthesise thyroxine, which controls metabolism.",
        },
        {
            "question": "The parts of a neuron that receive impulses from other cells are the:",
            "options": ["Dendrites", "Axons", "Nerve endings", "Cell bodies"],
            "correct": 0,
            "explanation": "Dendrites receive impulses and carry them towards the cell body; the axon carries them away.",
        },
    ],
    "c10s-07": [
        {
            "question": "The method of reproduction in yeast is:",
            "options": ["Budding", "Binary fission", "Fragmentation", "Regeneration"],
            "correct": 0,
            "explanation": "Yeast reproduces by budding, where a small bud grows on the parent cell and later detaches.",
        },
        {
            "question": "Amoeba reproduces by:",
            "options": ["Binary fission", "Multiple fission", "Budding", "Fragmentation"],
            "correct": 0,
            "explanation": "Amoeba divides into two equal daughter cells by simple binary fission.",
        },
        {
            "question": "Potato is grown from its tuber because it reproduces by:",
            "options": ["Vegetative propagation", "Spore formation", "Pollination", "Fertilisation"],
            "correct": 0,
            "explanation": "The eyes of a potato tuber are buds that grow into new plants, an example of vegetative propagation.",
        },
        {
            "question": "DNA copying during reproduction is important because it:",
            "options": ["Provides variation in the offspring", "Prevents cell division", "Stops all mutations", "Reduces genetic material"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Slight errors in DNA copying introduce variations, which are the raw material for evolution.",
        },
        {
            "question": "In humans, fertilisation of the egg by the sperm takes place in the:",
            "options": ["Oviduct", "Ovary", "Uterus", "Vagina"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Fertilisation occurs in the oviduct (fallopian tube); the zygote then moves to the uterus for implantation.",
        },
        {
            "question": "If the body of a broken planaria grows into a complete new organism, this is called:",
            "options": ["Regeneration", "Fragmentation", "Budding", "Fission"],
            "correct": 0,
            "explanation": "Regeneration is the ability of some organisms like planaria and hydra to grow lost body parts into full new individuals.",
        },
    ],
    "c10s-08": [
        {
            "question": "The hereditary information is carried from parents to offspring by:",
            "options": ["Genes", "Proteins", "Vitamins", "Enzymes"],
            "correct": 0,
            "explanation": "Genes, the segments of DNA, carry the hereditary information from parents to offspring.",
        },
        {
            "question": "In peas, the tall trait (T) is dominant over dwarf (t). A plant with the genotype tt will be:",
            "options": ["Dwarf", "Tall", "Intermediate height", "Tall only in the F1 generation"],
            "correct": 0,
            "explanation": "Since dwarfness is recessive, the trait shows only when both alleles are t, giving a dwarf plant.",
        },
        {
            "question": "In Mendel's monohybrid cross, the phenotypic ratio of tall to dwarf plants in the F2 generation is:",
            "options": ["3:1", "1:1", "9:3:3:1", "1:2:1"],
            "correct": 0,
            "explanation": "Selfing the F1 (Tt x Tt) gives tall and dwarf plants in the phenotypic ratio 3:1.",
        },
        {
            "question": "The genotypic ratio obtained in the F2 generation of Mendel's monohybrid cross is:",
            "options": ["1:2:1", "3:1", "9:3:3:1", "1:1"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The F2 cross TT x Tt x tt gives the genotypic ratio 1:2:1 (one TT, two Tt, one tt).",
        },
        {
            "question": "Which of the following pairs are contrasting characters in pea plants?",
            "options": ["Tall and dwarf", "Tall and round", "Round and yellow", "Violet and green pod"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Contrasting characters are alternative forms of a trait, like tall versus dwarf or round versus wrinkled seeds.",
        },
        {
            "question": "In human beings, the sex of the child is determined by the:",
            "options": ["Sperm of the father", "Egg of the mother", "Mother's blood group", "Time of fertilisation"],
            "correct": 0,
            "explanation": "The father's sperm carries either an X or a Y chromosome; an XX combination gives a girl and XY a boy.",
        },
    ],
    "c10s-09": [
        {
            "question": "The image formed by a plane mirror is:",
            "options": ["Virtual and erect", "Real and inverted", "Virtual and inverted", "Real and erect"],
            "correct": 0,
            "explanation": "A plane mirror forms a virtual, erect image of the same size, at the same distance behind the mirror.",
        },
        {
            "question": "The speed of light in vacuum is about:",
            "options": ["3 x 10^8 m/s", "3 x 10^6 m/s", "3 x 10^10 m/s", "3 x 10^5 m/s"],
            "correct": 0,
            "explanation": "Light travels at about 3 x 10^8 m/s in vacuum, the fastest possible speed.",
        },
        {
            "question": "A concave mirror is used in:",
            "options": ["Shaving mirrors and headlights", "Rear-view mirrors of vehicles", "Shop security mirrors", "Street lamps"],
            "correct": 0,
            "explanation": "Concave mirrors produce magnified erect images when the object is close, so they are used as shaving mirrors.",
        },
        {
            "question": "The power of a lens of focal length 50 cm is:",
            "options": ["2 dioptre", "0.5 dioptre", "20 dioptre", "50 dioptre"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Power in dioptre = 100/(focal length in cm) = 100/50 = 2 D.",
        },
        {
            "question": "The refractive index of glass is 1.5. The speed of light in glass is:",
            "options": ["2 x 10^8 m/s", "3 x 10^8 m/s", "1.5 x 10^8 m/s", "4.5 x 10^8 m/s"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Speed in a medium = speed in vacuum / refractive index = 3 x 10^8 / 1.5 = 2 x 10^8 m/s.",
        },
        {
            "question": "The focal length of a plane mirror is:",
            "options": ["Infinity", "Zero", "Half its length", "One metre"],
            "correct": 0,
            "explanation": "A plane mirror has no curvature, so its focal length is infinite and its power is zero.",
        },
    ],
    "c10s-10": [
        {
            "question": "The ability of the eye lens to change its focal length to focus objects at different distances is called:",
            "options": ["Power of accommodation", "Persistent vision", "Dispersion", "Refraction"],
            "correct": 0,
            "explanation": "The ciliary muscles change the curvature of the eye lens, giving the eye its power of accommodation.",
        },
        {
            "question": "The sharp image of an object is formed by the eye on the:",
            "options": ["Retina", "Cornea", "Iris", "Lens"],
            "correct": 0,
            "explanation": "The eye lens focuses light onto the retina, where photoreceptors detect the image.",
        },
        {
            "question": "Myopia (short-sightedness) is corrected by using:",
            "options": ["A concave lens", "A convex lens", "A cylindrical lens", "No lens at all"],
            "correct": 0,
            "explanation": "In myopia the image forms in front of the retina, and a concave lens diverges the rays to focus on it.",
        },
        {
            "question": "Hypermetropia (long-sightedness) is corrected by using:",
            "options": ["A convex lens", "A concave lens", "A plane mirror", "A concave mirror"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "In hypermetropia the image forms behind the retina, and a convex lens converges the rays to focus on it.",
        },
        {
            "question": "The sky appears blue because of:",
            "options": ["Scattering of blue light by the atmosphere", "Reflection by the sea", "Dispersion by dust", "Absorption of red light"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Blue light is scattered more strongly than other colours by air molecules, so the sky appears blue.",
        },
        {
            "question": "A rainbow is formed due to:",
            "options": ["Dispersion of sunlight by water droplets", "Reflection by the ground", "Refraction by glass", "Scattering by dust"],
            "correct": 0,
            "explanation": "Water droplets disperse and reflect sunlight, splitting it into the seven colours of the rainbow.",
        },
    ],
    "c10s-11": [
        {
            "question": "The SI unit of resistance is:",
            "options": ["Ohm", "Volt", "Ampere", "Watt"],
            "correct": 0,
            "explanation": "Resistance is measured in ohms (symbol ohm), named after Georg Simon Ohm.",
        },
        {
            "question": "Ohm's law states that the potential difference across a conductor is proportional to the:",
            "options": ["Current flowing through it", "Resistance of the circuit", "Length of the conductor", "Time of flow"],
            "correct": 0,
            "explanation": "V = IR: for a given resistance, the potential difference is directly proportional to the current.",
        },
        {
            "question": "The SI unit of electric current is:",
            "options": ["Ampere", "Volt", "Ohm", "Coulomb"],
            "correct": 0,
            "explanation": "Current is the rate of flow of charge and is measured in amperes.",
        },
        {
            "question": "If the length of a uniform wire is doubled without changing its thickness, its resistance:",
            "options": ["Doubles", "Halves", "Stays the same", "Becomes four times"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Resistance is proportional to length, so doubling the length doubles the resistance.",
        },
        {
            "question": "An electric device draws a current of 0.5 A from a 220 V supply. The power consumed is:",
            "options": ["110 W", "440 W", "220 W", "55 W"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "P = V x I = 220 x 0.5 = 110 W.",
        },
        {
            "question": "The filament of an electric bulb is made of tungsten because it has:",
            "options": ["A high melting point", "A low melting point", "Low resistance", "A blue colour"],
            "correct": 0,
            "explanation": "Tungsten's very high melting point lets the filament glow white-hot without melting.",
        },
    ],
    "c10s-12": [
        {
            "question": "Magnetic field lines emerge from the:",
            "options": ["North pole of a magnet", "South pole of a magnet", "Middle of a magnet", "Both poles equally"],
            "correct": 0,
            "explanation": "Field lines emerge from the north pole and enter the south pole outside a magnet.",
        },
        {
            "question": "The magnetic field lines around a straight current-carrying conductor are:",
            "options": ["Concentric circles", "Straight parallel lines", "Ellipses", "Parabolas"],
            "correct": 0,
            "explanation": "The field around a straight conductor forms concentric circles centred on the wire.",
        },
        {
            "question": "A coil of many circular turns of insulated copper wire wound on a cylindrical tube is called a:",
            "options": ["Solenoid", "Galvanometer", "Transformer", "Electroscope"],
            "correct": 0,
            "explanation": "A solenoid is a coil wound on a cylinder; it behaves like a bar magnet when current flows through it.",
        },
        {
            "question": "Electromagnetic induction was discovered by:",
            "options": ["Michael Faraday", "Isaac Newton", "Galileo Galilei", "James Watt"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Faraday discovered in 1831 that a changing magnetic field can induce a current in a circuit.",
        },
        {
            "question": "In an electric motor, the direction of force on a current-carrying conductor in a magnetic field is given by:",
            "options": ["Fleming's left-hand rule", "Fleming's right-hand rule", "Right-hand thumb rule", "Ohm's law"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "The left-hand rule gives the direction of force in a motor; the right-hand rule is used for induced current in a generator.",
        },
        {
            "question": "The frequency of the alternating current used in India is:",
            "options": ["50 Hz", "60 Hz", "100 Hz", "220 Hz"],
            "correct": 0,
            "explanation": "In India, household AC changes direction 100 times per second, giving a frequency of 50 Hz.",
        },
    ],
    "c10s-13": [
        {
            "question": "In a food chain, green plants are the:",
            "options": ["Producers", "Primary consumers", "Decomposers", "Top carnivores"],
            "correct": 0,
            "explanation": "Green plants make their own food by photosynthesis, so they are the producers.",
        },
        {
            "question": "A food chain always begins with:",
            "options": ["Producers", "Herbivores", "Carnivores", "Decomposers"],
            "correct": 0,
            "explanation": "Energy enters the ecosystem through producers, so every food chain starts with them.",
        },
        {
            "question": "The organisms that break down dead plants and animals into simple substances are:",
            "options": ["Bacteria and fungi", "Herbivores", "Carnivores", "Producers"],
            "correct": 0,
            "explanation": "Decomposers like bacteria and fungi recycle nutrients by breaking down dead organic matter.",
        },
        {
            "question": "The gradual increase in the concentration of a chemical (such as DDT) along a food chain is called:",
            "options": ["Biomagnification", "Biofertilisation", "Biodegradation", "Eutrophication"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "Non-biodegradable chemicals like DDT accumulate at each trophic level, a process called biomagnification.",
        },
        {
            "question": "The depletion of the ozone layer is mainly caused by:",
            "options": ["Chlorofluorocarbons (CFCs)", "Carbon dioxide", "Oxygen", "Nitrogen"],
            "correct": 0,
            "difficulty": "medium",
            "explanation": "CFCs released from refrigerators and air conditioners break down ozone molecules in the stratosphere.",
        },
        {
            "question": "Only about 10 percent of the energy available at one trophic level is transferred to the next. This is known as:",
            "options": ["The 10 percent law", "The law of dominance", "The law of segregation", "The law of inertia"],
            "correct": 0,
            "explanation": "Most energy is lost as heat during respiration and daily activities, so only about 10 percent passes to the next level.",
        },
    ],
}
